****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZT_211_DYNPRO																																
0200																																
753																																
                40																																
%_HEADER																																
ZT_211_DYNPRO                           0200 0300      0  0192 37  0  0 27120  0G E                              20231106230824																																
%_DESCRIPTION																																
SCREEN 200																																
%_FIELDS																																
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0200.																																
  MODULE SET_ALV.																																
																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0200.																																
