****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZT_211_DYNPRO																																
0100																																
753																																
                40																																
%_HEADER																																
ZT_211_DYNPRO                           0100 0200      5 22192 37  0  0 27121  0G E                              20231106231516																																
%_DESCRIPTION																																
SCREEN 100																																
%_FIELDS																																
%#AUTOTEXT001	0	CHAR	  9	00	00	00	30	00	  1	  4		  0	  0	  0		  0					  0	  0								ALV 시작?		
SFLIGHT-CARRID	2	CHAR	 16	30	00	04	30	00	  3	  4		  0	  0	  0		  0			CAR		  0	  0								Airline	                                                                                                                                                                                                                                                        X	
SFLIGHT-CARRID	C	CHAR	  3	A0	00	84	00	08	  3	 21		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
%#AUTOTEXT002		CHAR	  4	00	00	00	30	00	  5	  4		  0	  0	  0		  0	P				  0	  0	101							GOGO	                                                                                                                                                                        SELECT	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_0100.																																
																																
PROCESS AFTER INPUT.																																
 FIELD sflight-carrid.																																
 MODULE USER_COMMAND_0100.																																
